name: DEPLOY TO STAGING

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup nodejs
        uses: actions/setup-node@v1
      - name: Installing project dependencies
        run: npm install
      - name: Install Highcharts
        run: npm install highcharts
      - name: Building the project
        run: npm run build